<?php
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Customer\Model\ResourceModel\Address\Collection $addressCollection
 */
$addressCollection = $block->getData('customerAddressCollection');

$addressArray = [];
if ($block->getCustomerId()) {
    $addressArray = $addressCollection->setCustomerFilter([$block->getCustomerId()])->toArray();
}

/**
 * @var \Magento\Sales\ViewModel\Customer\AddressFormatter $customerAddressFormatter
 */
$customerAddressFormatter = $block->getData('customerAddressFormatter');

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address|\Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Address $block
 */

$defaultRegion = null;
$defaultDistrict = null;

if (!empty($block->getFormValues()['region_id'])) {
    $defaultRegion = $block->getFormValues()['region_id'];
}

if (!empty($block->getFormValues()['district'])) {
    $defaultDistrict = $block->getFormValues()['district'];
}

if ($block->getIsShipping()):
    $_fieldsContainerId = 'order-shipping_address_fields';
    $_addressChoiceContainerId = 'order-shipping_address_choice';
    ?>
    <script>
        require(["Magento_Sales/order/create/form"], function(){

            order.shippingAddressContainer = '<?= /* @escapeNotVerified */ $_fieldsContainerId ?>';
            order.setAddresses(<?= /* @escapeNotVerified */ $customerAddressFormatter->getAddressesJson($addressArray) ?>);

        });
    </script>
    <script>
        require(["Boolfly_GiaoHangNhanh/js/order/create/form/field/district"], function(district){
            district(
                {
                    defaultRegion: "<?= $defaultRegion ?>",
                    defaultDistrict: "<?= $defaultDistrict ?>",
                    jsonConfig: <?= $block->getAdditionalConfig()->getJsonData(); ?>
                }
            );
        });
    </script>
<?php
else:
    $_fieldsContainerId = 'order-billing_address_fields';
    $_addressChoiceContainerId = 'order-billing_address_choice';
    ?>
    <script>
        require(["Magento_Sales/order/create/form"], function(){
            order.billingAddressContainer = '<?= /* @escapeNotVerified */ $_fieldsContainerId ?>';
        });
    </script>
    <script>
        require(["Boolfly_GiaoHangNhanh/js/order/create/form/field/district"], function(district){
            district(
                {
                    defaultRegion: "<?= $defaultRegion ?>",
                    defaultDistrict: "<?= $defaultDistrict ?>",
                    jsonConfig: <?= $block->getAdditionalConfig()->getJsonData(); ?>,
                    districtInput: '#order-billing_address_district',
                    districtSelector: '#order-billing_address_district_id',
                    regionSelector: '#order-billing_address_region_id',
                    addressBox: '#order-billing_address_fields',
                    districtSelectorID: 'order-billing_address_district_id'
                }
            );
        });
    </script>
<?php
endif; ?>

<fieldset class="admin__fieldset">
    <legend class="admin__legend <?= /* @escapeNotVerified */ $block->getHeaderCssClass() ?>">
        <span><?= /* @escapeNotVerified */ $block->getHeaderText() ?></span>
    </legend><br>

    <fieldset id="<?= /* @escapeNotVerified */ $_addressChoiceContainerId ?>" class="admin__fieldset order-choose-address">
        <?php if ($block->getIsShipping()): ?>
            <div class="admin__field admin__field-option admin__field-shipping-same-as-billing">
                <input type="checkbox" id="order-shipping_same_as_billing" name="shipping_same_as_billing"
                       onclick="order.setShippingAsBilling(this.checked)" class="admin__control-checkbox"
                       <?php if ($block->getIsAsBilling()): ?>checked<?php endif; ?> />
                <label for="order-shipping_same_as_billing" class="admin__field-label">
                    <?= /* @escapeNotVerified */ __('Same As Billing Address') ?>
                </label>
            </div>
        <?php endif; ?>
        <div class="admin__field admin__field-select-from-existing-address">
            <label class="admin__field-label"><?= /* @escapeNotVerified */ __('Select from existing customer addresses:') ?></label>
            <?php $_id = $block->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
            <div class="admin__field-control">
                <select id="<?= /* @escapeNotVerified */ $_id ?>"
                        name="<?= $block->getForm()->getHtmlNamePrefix() ?>[customer_address_id]"
                        onchange="order.selectAddress(this, '<?= /* @escapeNotVerified */ $_fieldsContainerId ?>')"
                        class="admin__control-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Add New Address') ?></option>
                    <?php foreach ($addressArray as $addressId => $address): ?>
                        <option
                            value="<?= /* @escapeNotVerified */ $addressId ?>"<?php if ($addressId == $block->getAddressId()): ?> selected="selected"<?php endif; ?>>
                            <?= /* @escapeNotVerified */ $block->escapeHtml($customerAddressFormatter->getAddressAsString($address)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </fieldset>

    <div class="order-address admin__fieldset" id="<?= /* @escapeNotVerified */ $_fieldsContainerId ?>">
        <?= $block->getForm()->toHtml() ?>

        <div class="admin__field admin__field-option order-save-in-address-book">
            <input name="<?= $block->getForm()->getHtmlNamePrefix() ?>[save_in_address_book]" type="checkbox" id="<?= $block->getForm()->getHtmlIdPrefix() ?>save_in_address_book" value="1"
                <?php if (!$block->getDontSaveInAddressBook()): ?> checked="checked"<?php endif; ?> class="admin__control-checkbox"/>
            <label for="<?= $block->getForm()->getHtmlIdPrefix() ?>save_in_address_book"
                   class="admin__field-label"><?= /* @escapeNotVerified */ __('Save in address book') ?></label>
        </div>
    </div>
    <?php $hideElement = 'address-' . ($block->getIsShipping() ? 'shipping' : 'billing') . '-overlay'; ?>
    <div style="display: none;" id="<?= /* @escapeNotVerified */ $hideElement ?>" class="order-methods-overlay">
        <span><?= /* @escapeNotVerified */ __('You don\'t need to select a shipping address.') ?></span>
    </div>

    <script>
        require(["Magento_Sales/order/create/form"], function(){
            order.bindAddressFields('<?= /* @escapeNotVerified */ $_fieldsContainerId ?>');
            order.bindAddressFields('<?= /* @escapeNotVerified */ $_addressChoiceContainerId ?>');
            <?php if ($block->getIsShipping() && $block->getIsAsBilling()): ?>
            order.disableShippingAddress(true);
            <?php endif; ?>
        });
    </script>
</fieldset>
